# Generated by Django 5.2.11 on 2026-04-11 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_useraddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'ordering': ['-is_default', '-created_at'], 'verbose_name': 'User Address', 'verbose_name_plural': 'User Addresses'},
        ),
        migrations.AddField(
            model_name='useraddress',
            name='title',
            field=models.CharField(default=1, help_text='Ev, İş, Digər', max_length=100, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=models.CharField(max_length=10, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Default'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
